name: customprompt
description: Customprompt is a simple animated modal dialog for flutter IOS, Android and Web apps.
version: 0.2.7+3
homepage: https://github.com/Muchwat/Custom-Prompt

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
